### ISSUE TITLE
'thrift --gen swift_3 thrift_file' not working

### ISSUE THREAD

**Issue by gaoshanyu** [apocolipse/Thrift-Swift#10]
When I use the command will get error:

> sh: thrift-gen-swift_3: command not found
plugin process returned non zero exit code: 32512
[WARNING:generation:1] Plugin generator for "swift_3" failed.

**Comment by wyland** [comment]
Hello

Can you please confirm you are using the updated generator? A link to the source is documented in latest tag as a breaking change here: https://github.com/apocolipse/Thrift-Swift/releases/tag/1.0.7

**Comment by gaoshanyu** [comment]
Hi, I tried to build the generator http://github.com/apocolipse/thrift, but met error: "Error: libcrypto required."

**Comment by wyland** [comment]
Ok to close? Or are there any remaining open questions in this issue?
