### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by AndrewSB** [apocolipse/Thrift-Swift#13]
I'm trying to use this library in Swift 4. From what I see, there exist forks that have upgraded to swift 4 (https://github.com/apocolipse/Thrift-Swift/network). See https://github.com/Petro-Lomaka/Thrift-Swift, for example.
The framework they vend seems to work for me.

The command line `thrift`, on the other hand, seems not to. I'm trying to use @Petro-Lomaka's fork (same guy), but the generated code doesn't conform to the Thrift swift module. I'm currently trying to uninstall my thrift, then reinstall from brew, and then follow the instructions in #11 with the `thrift ` fork.

Can we start the process of moving this library to swift 4?

**Comment by AndrewSB** [comment]
From what I see, no one has updated the thrift fork, so the generated code is not currently usable in swift 4

**Comment by Petro-Lomaka** [comment]
I have forked repo for tests. Look into feature branch.
----
`generated code is not currently usable in swift 4`
Xcode 9 supports Swift3.2 and Swift4. So generated code can be easily used in the project. There are some issues you should fix manualy.

**Comment by AndrewSB** [comment]
But that means I'll need to switch all my code to swift 3.2, right? I can't use swift 4 in other targets?

**Comment by AndrewSB** [comment]
Also, swift 3.2 doesn't work either. I switched my target to be swift 3.2, the errors reduce, but there are still 144+

<img width="1401" alt="screen shot 2017-10-23 at 11 41 00 am" src="https://user-images.githubusercontent.com/3814772/31906904-29fb99b8-b7e7-11e7-8156-376376b54637.png">

**Comment by Petro-Lomaka** [comment]
Not related to Swift4

**Comment by AndrewSB** [comment]
apocolipse's repositories currently support swift 4, I apologize for my confusion

**Comment by wyland** [comment]
Ok to close? Or are there any remaining open questions in this issue?
