### ISSUE TITLE
Let all socket communication go through a 3rd party library. 

### ISSUE THREAD

**Issue by seivan** [apocolipse/Thrift-Swift#23]
It's slightly related to https://github.com/apocolipse/Thrift-Swift/issues/21 

I'd like to see UDP support, but at the same time I'm not comfortable adding that myself since I'm pretty sure there's a lot of edge cases to tackle (especially when it comes to UDP). One thing I found that is that the on board radio on iPhones do not activate when using UDP, and you need to kick start it by using TCP first. 

By using something like `IBM/BlueSocket` it would be easier to add support for both UDP and TCP by letting a different component handle network details.

**Comment by EMCP** [comment]
Thrift itself doesn't support UDP.. so I think you might be wanting something which wouldn't make much sense for this project

https://github.com/apache/thrift/blob/master/doc/images/thrift-layers.png

https://github.com/apache/thrift
