### ISSUE TITLE
/opt/local/dev/Thrift-Swift: error: package at '/opt/local/dev/Thrift-Swift' is using Swift tools version 3.1.0 which is no longer supported; use 4.0.0 or newer instead

### ISSUE THREAD

**Issue by TyrfingMjolnir** [apocolipse/Thrift-Swift#25]
$ swift build
/opt/local/dev/Thrift-Swift: error: package at '/opt/local/dev/Thrift-Swift' is using Swift tools version 3.1.0 which is no longer supported; use 4.0.0 or newer instead

$ swift -version
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.6.0

**Comment by wyland** [comment]
Feel free to use the `swift4` or `swift4.2` branches which are using the respective `.swift-version` and package manifest.

You may need to install the appropriate swift toolchain using something like `swiftenv` to get this to build on the CLI

**Comment by wyland** [comment]
@TyrfingMjolnir Any more questions or can we close this?
