### ISSUE TITLE
Enum failable initialization / tag 1.0.7

### ISSUE THREAD

**Issue by Petro-Lomaka** [apocolipse/Thrift-Swift#6]
Hello!
 Faced with issue (**tag 1.0.7**):  `'nil' is the only return value permitted in an initializer`
 
Enum in my .thrift file:
```
enum Gender {
	M = 0,
	F = 1
}
```

Thrift generated code:
![enum-failable-init](https://user-images.githubusercontent.com/8578402/27579468-4b3a8dd2-5b30-11e7-8627-4661d953d678.png)

**Comment by wyland** [comment]
Hello

Can you please confirm you are using the updated generator? A link to the source is documented in latest tag as a breaking change here: https://github.com/apocolipse/Thrift-Swift/releases/tag/1.0.7

This should generate with a `nil` in that version.

**Comment by Petro-Lomaka** [comment]
@wyland Thanks. Latest tag fixed this issue.
