### ISSUE TITLE
Enum property access level / tag 1.0.7

### ISSUE THREAD

**Issue by Petro-Lomaka** [apocolipse/Thrift-Swift#7]
Hello!

Faced with error (**tag 1.0.7**):  `Property 'rawValue' must be declared public because it matches a requirement in public protocol 'TEnum'`

Enum in my .thrift file:

```
enum Gender {
	M = 0,
	F = 1
}
```

Thrift generated code:

![enum-property-access-level](https://user-images.githubusercontent.com/8578402/27579581-b3e62292-5b30-11e7-81f3-7cd71338f57f.png)

**Comment by wyland** [comment]
Hello

Can you please confirm you are using the updated generator? A link to the source is documented in latest tag as a breaking change here: https://github.com/apocolipse/Thrift-Swift/releases/tag/1.0.7

This should generate the `public` in your case.
